#!/usr/bin/perl -w
use strict;
use DBI;

my $dbpath = $ENV{"HOME"} . "/.config";

die ("no .config in HOME?") if (!-d $dbpath);

$dbpath .= '/slucto';

if (!-d $dbpath) {
	mkdir($dbpath) || die "cannot create slucto dir in .config";
}

my $out = $dbpath . '/slucto.db';

if (-e $out) {
	my $reply = "N";
	do {
		print "'$out' already exists, overwrite? [y/N] ";
		$reply = uc(<STDIN>);
		chomp($reply);
	} while ($reply ne "Y" && $reply ne "N" && $reply ne "");
	exit 1 if ($reply ne "Y");
	unlink $out;
}

my $dbh = DBI->connect("dbi:SQLite:dbname=$out","","", {AutoCommit => 0}) ||
	die "connect to db error: " . DBI::errstr;

$dbh->do("PRAGMA foreign_keys = ON") || die "cannot set foreign keys";

$dbh->do("CREATE TABLE prijemce(ic INTEGER PRIMARY KEY, " .
	"nazev STRING NOT NULL, ulice STRING NOT NULL, " .
	"mesto STRING NOT NULL, " .
	"psc STRING NOT NULL)");

$dbh->do("CREATE TABLE faktura(id INTEGER PRIMARY KEY, " .
	"prijemce INTEGER NOT NULL, " .
	"vystaveni INTEGER NOT NULL, splatnost INTEGER NOT NULL, " .
	"FOREIGN KEY(prijemce) REFERENCES prijemce(ic))");

$dbh->do("CREATE TABLE polozka(id INTEGER PRIMARY KEY, " .
	"nazev STRING NOT NULL UNIQUE, cena REAL)");

$dbh->do("CREATE TABLE faktura_polozka(id_faktura INTEGER NOT NULL, " .
		"id_polozka INTEGER NOT NULL, pocet INTEGER NOT NULL, " .
		"cena REAL NOT NULL, poznamka STRING, " .
		"UNIQUE(id_faktura, id_polozka, poznamka), " .
		"FOREIGN KEY(id_faktura) REFERENCES faktura(id), " .
		"FOREIGN KEY(id_polozka) REFERENCES polozka(id))");

my $data = $dbh->prepare("INSERT INTO prijemce(nazev, ulice, mesto, psc, ic) " .
		"VALUES (?, ?, ?, ?, ?)");
$data->execute("PC-DIR Real, s.r.o.", "Mlýnská 425/70", "Brno", "602 00",
	25533525);
$data->finish;

$data = $dbh->prepare("INSERT INTO faktura(id, prijemce, vystaveni, " .
	"splatnost) VALUES (?, ?, ?, ?)");
$data->execute(201703001, 25533525, time, time + 3600*24*14);
$data->finish;

$data = $dbh->prepare("INSERT INTO polozka(nazev, cena) VALUES (?, ?)");
$data->execute("Školení pro 2 osoby/den", 3200);
$data->execute("Školení pro 3 osoby/den", 3600);
$data->execute("Školení pro 4 a více osob/den", 4200);
$data->finish;

$data = $dbh->prepare("INSERT INTO faktura_polozka(id_faktura, id_polozka, " .
	"pocet, poznamka, cena) SELECT ?, id, ?, ?, cena FROM polozka " .
	"WHERE id = ?");
$data->execute(201703001, 3, 'v termínu 8-10. 3. 2017', 3);
$data->finish;

$dbh->commit;

$dbh->disconnect;

1;
